language: python
sudo: false
cache: pip
dist: xenial
matrix:
  include:
    - python: "3.8"
install:
  - pip install tox-travis codecov
script:
  - tox -v
after_success:
  - codecov
notifications:
  email: false
